// Teksten van de widgets (EN en NL). Kort, exact, rustig: geen uitroeptekens, geen emoji, geen streepjes.
import { lang } from '@/i18n';

const en = {
  ok: 'OK',
  warning: 'WARNING',
  warningShort: 'WARNING',
  critical: 'CRITICAL',
  offline: 'OFFLINE',
  cpu: 'CPU',
  ram: 'RAM',
  swap: 'SWAP',
  temp: 'TEMP',
  disk: 'DISK',
  disks: 'DISKS',
  fan: 'FAN',
  services: 'SERVICES',
  containers: 'CONTAINERS',
  sites: 'SITES',
  backup: 'BACKUP',
  updates: 'UPDATES',
  network: 'NETWORK',
  in: 'IN',
  out: 'OUT',
  load: 'LOAD',
  uptime: 'UPTIME',
  io: 'I/O',
  read: 'R',
  write: 'W',
  events: 'OPEN EVENTS',
  fleet: 'FLEET',
  peak: 'PEAK 24H',
  cores: 'CORES',
  smart: 'SMART',
  up: 'UP',
  down: 'DOWN',
  running: 'RUNNING',
  stopped: 'STOPPED',
  unhealthy: 'UNHEALTHY',
  latency: 'LATENCY',
  jobs: 'JOBS',
  failedLabel: 'FAILED',
  oldLabel: 'OLD',
  lastUpdate: 'last update',
  ago: 'ago',
  held: 'held',
  free: 'free',
  failing: 'failing',
  servers: (n: number) => `${n} ${n === 1 ? 'server' : 'servers'}`,
  more: (n: number) => `+${n} more`,
  noIssues: 'No open issues',
  noSites: 'No sites monitored',
  noContainers: 'No containers',
  noBackups: 'No backups found',
  alarmLong: (d: string) => `Disk ${d} shows signs of failure`,
  alarmShort: (d: string) => `Disk ${d} failing`,
  alarmTiny: (d: string) => `${d} failing`,
  setup: 'Open Nex Pi Control to connect your Pi',
  setupShort: 'Connect your Pi',
  agent: 'agent',
  min: 'min',
  hour: 'h',
  day: 'd',
};

const nl: typeof en = {
  ok: 'OK',
  warning: 'WAARSCHUWING',
  warningShort: 'LET OP',
  critical: 'KRITIEK',
  offline: 'OFFLINE',
  cpu: 'CPU',
  ram: 'RAM',
  swap: 'SWAP',
  temp: 'TEMP',
  disk: 'SCHIJF',
  disks: 'SCHIJVEN',
  fan: 'FAN',
  services: 'DIENSTEN',
  containers: 'CONTAINERS',
  sites: 'SITES',
  backup: 'BACKUP',
  updates: 'UPDATES',
  network: 'NETWERK',
  in: 'IN',
  out: 'UIT',
  load: 'LOAD',
  uptime: 'UPTIME',
  io: 'I/O',
  read: 'L',
  write: 'S',
  events: 'OPEN MELDINGEN',
  fleet: 'VLOOT',
  peak: 'PIEK 24U',
  cores: 'KERNEN',
  smart: 'SMART',
  up: 'UP',
  down: 'DOWN',
  running: 'ACTIEF',
  stopped: 'GESTOPT',
  unhealthy: 'ONGEZOND',
  latency: 'LATENTIE',
  jobs: 'TAKEN',
  failedLabel: 'MISLUKT',
  oldLabel: 'OUD',
  lastUpdate: 'laatste update',
  ago: 'geleden',
  held: 'vastgehouden',
  free: 'vrij',
  failing: 'faalt',
  servers: (n: number) => `${n} servers`,
  more: (n: number) => `+${n} meer`,
  noIssues: 'Geen open problemen',
  noSites: 'Geen sites bewaakt',
  noContainers: 'Geen containers',
  noBackups: 'Geen backups gevonden',
  alarmLong: (d: string) => `Schijf ${d} vertoont tekenen van falen`,
  alarmShort: (d: string) => `Schijf ${d} faalt`,
  alarmTiny: (d: string) => `${d} faalt`,
  setup: 'Open Nex Pi Control om je Pi te koppelen',
  setupShort: 'Koppel je Pi',
  agent: 'agent',
  min: 'min',
  hour: 'u',
  day: 'd',
};

export type Copy = typeof en;
export const copy: Copy = lang === 'nl' ? nl : en;
